In [2]:
import numpy as np

In [3]:
my_list=[1,2,3]
print(my_list)
print(type(my_list))
my_array=np.array(my_list)
print(my_array)
print(type(my_array))
my_nestedlist=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix=np.array(my_nestedlist)
print(my_matrix)
arr=np.arange(0,11)
print(arr)


[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
Zero_matrix=np.zeros(5)
print(Zero_matrix)
one_matrix=np.ones(5)
print(one_matrix)
linear_space=np.linspace(0,10)
my_range=np.arange(0,10,3)
print(linear_space)
print(my_range)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 0.          3.33333333  6.66666667 10.        ]
[0 3 6 9]


In [14]:
identity_matrix=np.eye(4,4)
print(identity_matrix)
I=np.zeros((2,3))
print(I)
Reshaped=I.reshape(3,2)
print(Reshaped)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
matrix_1=np.arange(1,10)
print(matrix_1)
matrix_2=matrix_1.reshape(3,3)
print(matrix_2)
matrix_2[:,[0,1]]=matrix_2[:,[1,0]]
print(matrix_2)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [7]:
np.random.seed(42)
Random=np.random.rand(1)
print(Random)
Rand_Int=np.random.randint(0,20,(4,5))

print(Rand_Int)


[0.37454012]
[[14 10  7  6 18]
 [10 10  3  7  2]
 [ 1 11  5  1  0]
 [11 11 16  9 15]]


In [19]:
arr=np.full((4,4),5)
print(arr)
arr=np.ones(5)
arr2=arr*5

print(arr2)



[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[5. 5. 5. 5. 5.]


In [9]:
arr=np.arange(1,11)
arr2=np.where(arr%2==1,1,arr)
print(arr2)

[ 1  2  1  4  1  6  1  8  1 10]


In [22]:
arr=np.arange(1,101)
arr[:11]=5
print(arr)

[  5   5   5   5   5   5   5   5   5   5   5  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
