In [3]:
import numpy as np
Z=np.random.random(10)
print(Z)

[0.54657725 0.96787295 0.71180456 0.63376908 0.71607193 0.02703707
 0.26698855 0.48360527 0.20404863 0.66579901]


In [4]:
import math 
Result=math.sqrt(25)
print(Result)

5.0


In [5]:
import demo as d
greet=d.greet()


Hello, World!


In [6]:
import importlib
from importnb import Notebook

with Notebook():
    import Day05 as D


In [7]:
Z=D.sum_of_digits(1234
)
print(Z)

10


In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9])

arr.argmax()
arr.argmin()

np.int64(0)

In [9]:
Z=np.random.random(20)
Z[Z.argmax()]=0
Z[Z.argmin()]=1
print(Z)

[0.87748741 0.65588884 0.09834206 0.95323355 0.19268738 0.6566635
 0.77137317 0.1495632  0.59841646 0.80416877 0.2225282  0.21673802
 0.94207771 0.51488583 1.         0.46389909 0.52820115 0.41743926
 0.02143959 0.17396287]


In [ ]:
Z=np.arange(1,101)
Z[:11]=5
print(Z)
#arr(4,4)    arr[start:stop:step,start:stop:step]

[  5   5   5   5   5   5   5   5   5   5   5  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [11]:
a=np.tile([1,2,3,4,5,6,7,8,9,10],10)
print(Z)

[  5   5   5   5   5   5   5   5   5   5   5  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [12]:
a=np.repeat([1,2,3,4,5,6,7,8,9,10],10)
print(a)

[ 1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  3  3  3  3
  3  3  3  3  3  3  4  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5
  5  5  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  7  8  8
  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9  9  9 10 10 10 10 10 10
 10 10 10 10]


In [13]:
Z=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:

print(Z[0:2,1:])



[[2 3]
 [5 6]]


In [15]:
lst=[1,2,3,4,5,6,7,8,9]
print(lst[2::3])

[3, 6, 9]


In [16]:
Z=np.arange(1,101)
print(Z[Z%7==0])

[ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]


In [17]:
print(Z>10)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


In [18]:
print(len(Z))

100


In [19]:
Z1=np.arange(0,10)
Z2=np.arange(10,20)
print(Z1+Z2)

[10 12 14 16 18 20 22 24 26 28]


In [20]:
Z1/Z1

C:\Users\prajval gupta\AppData\Local\Temp\ipykernel_19976\2297827168.py:1: RuntimeWarning: invalid value encountered in divide
  Z1/Z1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [21]:
print(np.nan<0)
print(np.nan>0)

False
False


In [22]:
a=np.arange(1,10)
b=np.arange(10,19)
np.add(a,b,out=a)
print(a)


[11 13 15 17 19 21 23 25 27]
